### ISSUE TITLE
Prevent Steiner insertion + Thread re-insertion safety

### ISSUE THREAD

**Issue by Vilo176** [NGSolve/netgen#105]
Hi friends,

1. Is there a way, by means of the C++ API, to use NetGen to tetrahedralize a single triangulated Mesh, but preventing any steiner point insertion (i.e. preserving given triangulation) ?

2. Is it possible to tetrahedralize N independent meshes concurrently (i.e, each one from a different thread) ?

Thanks in advance.

**Comment by ChrLackner** [comment]
Hi, netgen always preserves surface triangulation.
2. Yes, should be possbile (we do it for volume meshing to mesh each domain seperately and then merge the meshes)
