### ISSUE TITLE
netgen nglib for web app (js)

### ISSUE THREAD

**Issue by yvanblanchard** [NGSolve/netgen#145]
Hello,

I guess you have now a web GUI engine in JS for netgen mesher (used for Jupyter Notenook usage). 
Could it be possible to get access to the js/html source code for customization purpose in this github repo ?

Thank you.

**Comment by ChrLackner** [comment]
Hi,
the webgui code can be found here: https://github.com/CERBSim/webgui

the jupyter widget integration here: https://github.com/CERBSim/webgui_jupyter_widgets
