### ISSUE TITLE
Overriding NetgenGeometry::GetFaceVertices doesn't work

### ISSUE THREAD

**Issue by MrSmile** [NGSolve/netgen#177]
I'm using generic meshing interface by creating derivative class from `netgen::NetgenGeometry`. I want to add specific points to the final mesh, but overriding `NetgenGeometry::GetFaceVertices` doesn't seem to have any effect. Corresponding parts of the source code for [generic interface](https://github.com/NGSolve/netgen/blob/master/libsrc/meshing/basegeom.cpp#L765) and [OCC](https://github.com/NGSolve/netgen/blob/master/libsrc/occ/occgenmesh.cpp#L301) look different too. I tried to port OCC variant, i.e.
```patch
--- a/libsrc/meshing/basegeom.cpp
+++ b/libsrc/meshing/basegeom.cpp
@@ -775,7 +775,10 @@ namespace netgen
         PointIndex pi = vert->nr + 1;
         if(glob2loc[pi] == 0)
           {
-            meshing.AddPoint(mesh[pi], pi);
+            auto gi = face.Project(mesh[pi]);
+            MultiPointGeomInfo mgi;
+            mgi.AddPointGeomInfo(gi);
+            meshing.AddPoint(mesh[pi], pi, &mgi);
             cntp++;
             glob2loc[pi] = cntp;
           }
```
and problem resolves. Is it a bug or I'm missing something?

**Comment by ChrLackner** [comment]
Yes indeed. The baseclass implementation was done some years ago exactly to be able to couple other kernels as well. But not everything that has been changed in occ has made it there yet. And it is also not really tested (except the parts that occ uses).
I've commited these changes to master. Thanks for reporting
