### ISSUE TITLE
TaskManager leaks NodeData

### ISSUE THREAD

**Issue by roystgnr** [NGSolve/netgen#190]
`nodedata[0]` (and others `#ifdef USE_NUMA`) is allocated via `new` in the `TaskManager` constructor, but never deleted in the destructor (whereas `trace`, the other static variable pointing to a heap allocation, is).  

It looks like `TaskManager` is intended to be a singleton, in which case this obviously isn't a serious leak, just something I noticed while using sanitizer tools to try to hunt down something more serious.

**Comment by mhochsteger** [comment]
Thanks for reporting, this is fixed with 508136b533324312ae08c40a0eb86facf23e6416.
