### ISSUE TITLE
Compilation fails with PREFER_SYSTEM_PYBIND11=ON on some Linux distributions

### ISSUE THREAD

**Issue by marioalexis84** [NGSolve/netgen#194]
Since https://github.com/NGSolve/netgen/commit/c7800704b0c08f6b686ce8b7347905d89eb20002 it is not possible to compile with system pybind11 provided by some Linux distributions. For example, Debian provides pybind11 2.10.3 and `py::set_error` function was added in pybind11 2.12.
Is it possible to use another strategy to handle that error so that older versions of pybind11 can be used?

**Comment by ChrLackner** [comment]
Should be fixed now.
