### ISSUE TITLE
[Windows] Possibly missing DLL_HEADER

### ISSUE THREAD

**Issue by thinks** [NGSolve/netgen#199]
We are building netgen using the following steps:

```
cmake.exe -DCMAKE_INSTALL_PREFIX=C:/temp/netgen -DCMAKE_BUILD_TYPE=Release -DUSE_OCC=OFF -DUSE_PYTHON=OFF -DUSE_GUI=OFF -SC:/git/netgen -Bc:/git/netgen/build -G "Visual Studio 17 2022" -T host=x86 -A x64

cmake.exe --build . --target install
```

However, when we try to link against the shared libraries we get some linker errors. Among other things the linker cannot find symbols for the [Solid](https://github.com/NGSolve/netgen/blob/master/libsrc/csg/solid.hpp) class methods that are defined in the cpp-file. 

It seems that these issues can be fixed by adding the DLL_HEADER macro, e.g. `class DLL_HEADER Solid`. I'm wondering if this is simply an oversight, or if there is some deeper design decision behind the omission of the macro in this case.

When using `dumpbin /exports nglib.dll` we can confirm that the symbols for the `Solid` class have indeed not been exported.

Cheers,
T

**Comment by ChrLackner** [comment]
This is mostly because I think noone uses netgen-csg from the C++ side (on windows) and therefore hasn't been added. Currently csg is not really actively developed any more and has been replaced mostly by opencascade bindings.

**Comment by thinks** [comment]
Thanks for your rapid response! We will likely end up patching the source code locally to fit our needs. Closing this issue.
