### ISSUE TITLE
Two Free Solids volumic meshing produces two volumic meshes

### ISSUE THREAD

**Issue by jobordu** [NGSolve/netgen#29]
Dear Netgen Community, 

It seems there is a different behavior if you specify your geometry using CSG format  (.geo) or if you use OpenCASCADE CAD format (.step with colors).

I have a .step geometry made of two solids - a sphere and a box. The sphere is fully contained within the box. It is similar to the trafo.geo example where 4 different solids are fully contain within one box: https://github.com/NGSolve/netgen/blob/master/tutorials/trafo.geo  

As it is the case with the trafo.geo example, my goal is to have a single volume mesh where the surface boundary is respected by the volume mesh and where all Tet elements are connected to each others. 

However, what is obtain is a simple append of two unconnected volume mesh, one for the sphere and one for the box. 

The .step file is include in the sphere_in_cube.zip file here attached: 
[sphere_in_cube.zip](https://github.com/NGSolve/netgen/files/2938470/sphere_in_cube.zip)

Result of a connectivity filter in Paraview shows two distinct unconnected volume mesh:
![image](https://user-images.githubusercontent.com/10748104/53916618-8ece3f80-4030-11e9-9786-6951218801c0.png)

**Comment by trelau** [comment]
I would expect the need for a Boolean operation in OpenCASCADE to split the box with the sphere resulting in a single, but non-manifold, shape. Then the topology (and associated mesh) should be shared between the domains.
