### ISSUE TITLE
netgen -batchmode not passing filenames in -geofile

### ISSUE THREAD

**Issue by boyle** [NGSolve/netgen#34]
When calling `netgen -batchmode -geofile=xyz.geo` the `xyz.geo` was not passing out to `ng.tcl`. I guess the Tcl interpreter was swallowing the string before it got back out to the `ng.tcl` at line 156. It needs to be copied before being passed.

`set geofilename [Ng_GetCommandLineParameter geofile]`

Tcl version 8.6. Ubuntu 18.04. Latest git revision: commit 15e68020ba.

The fix:
```
diff --git a/ng/ngpkg.cpp b/ng/ngpkg.cpp
index 102208c..e18db3c 100644
--- a/ng/ngpkg.cpp
+++ b/ng/ngpkg.cpp
@@ -1302,7 +1302,7 @@ namespace netgen
 
     if (parameters.StringFlagDefined (argv[1]))
       Tcl_SetResult (interp,
-                    (char*)parameters.GetStringFlag (argv[1], NULL).c_str(), TCL_STATIC);
+                    (char*)parameters.GetStringFlag (argv[1], NULL).c_str(), TCL_VOLATILE);
     else if (parameters.NumFlagDefined (argv[1]))
       {
        sprintf (buf, "%lf", parameters.GetNumFlag (argv[1], 0));
```

**Comment by mhochsteger** [comment]
Fixed with commit 287256a6
