### ISSUE TITLE
Question: what is the C++ equivalent of `mesh.Export()`

### ISSUE THREAD

**Issue by miho** [NGSolve/netgen#43]
What is the C++ equivalent to 

```
mesh.Export("export.stl")
```

or

```
mesh.Export("export.msh","Gmsh Format")
```

For me, the python binding is not self explanatory. Is there documentation on how to convert between the supported volume/surface formats?

Thanks!

**Comment by ChrLackner** [comment]
The equivalent c++ function is WriteUserFormat in libsrc/interface/writeuser.cpp it dispatches to the different format functions.
You can try to import the mesh using ImportMesh and then use mesh.Export for this.

**Comment by stenfalp** [comment]
I wasn't able to use the WriteUserFormat function. I copied the code of the function WriteSTLFormat in my code instead.
If you have found how to do it, please let me know.

Thanks.
