### ISSUE TITLE
Unconditional include (on non windows) of x86intrin.h breaks other arches

### ISSUE THREAD

**Issue by hobbes1069** [NGSolve/netgen#44]
In libsrc/core/utils.hpp, x86intrin.h is included on all non-windows systems which breaks building on other arches, names ppc64le, s390x, and arm. 

Perhaps a solution as adviced here would work, but my understanding an alternative to the instric will need to be provided.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861754

**Comment by mhochsteger** [comment]
I have no such machine to test, but the branch no_x86 should resolve your issue:
https://github.com/NGSolve/netgen/commit/07758ce7a7237677408bc85ee08df61e82c09a63

**Comment by hobbes1069** [comment]
Traveling for work right now but I'll test when I get home.

**Comment by hobbes1069** [comment]
Just found this again after completely forgetting about it. It looks like another solution was upstreamed a while ago.
