### ISSUE TITLE
Incremental meshing on existing tetrahedron meshes

### ISSUE THREAD

**Issue by liubenyuan** [NGSolve/netgen#45]
Hi,

Is netgen capable of generating incremental meshes on existing tetrahedron meshes? I want to add some electrode patch on a cylinder (which is a simple binary, existing tetrahedron mesh).

Benyuan

**Comment by ChrLackner** [comment]
Not trivially, but you can merge existing surface (and volume) meshes or mesh domains seperately. For example salome has built this in in their interface to netgen.
Do you need to keep the structure of the mesh for some reasons?

**Comment by liubenyuan** [comment]
Yes, I have a fine-grained head mesh (http://www.parralab.org/nyhead/) and we want to add electrodes (a small cylinder with its top face as the boundary conditions. Electrical current flows into this bc which accounts for Neumann condition) around it.

However, we would like to add electrodes at different locations and evaluate the performance of transcranial Electrical Stimulation (tES), for example, the depth or the active regions. We would like to conduct FEM simulation using ngsolve.

**Comment by ChrLackner** [comment]
You can merge meshes and only partially mesh volume meshes. There is some documentation on these features here
https://ngsolve.org/docu/latest/netgen_tutorials/working_with_meshes.html

If you have a (partially meshed mesh) it should be possible to mesh the open domains using 
mesh.GenerateVolumeMesh(only3D_domain_nr=domnr)

Hope this helps
Best
