### ISSUE TITLE
lapack download link in "/cmake/SuperBuild.cmake" is failure

### ISSUE THREAD

**Issue by 9Ajiang** [NGSolve/netgen#47]
"http://www.asc.tuwien.ac.at/~mhochsteger/ngsuite/lapack64.zip" this link in SuperBuild.cmake is unreachable. There are any alternative way to solve this problem?

**Comment by mhochsteger** [comment]
The link is working for me. Anyway, I moved the file to github and adapted the link, this should increase the availability, see
https://github.com/NGSolve/ngsolve/commit/718071838eb55da39b6f9c120d7fe36402f4e68a

**Comment by 9Ajiang** [comment]
Thanks
