### ISSUE TITLE
Ng_DeleteMesh - crash

### ISSUE THREAD

**Issue by mv740** [NGSolve/netgen#52]
Hi, 

I am using netgen to load a step file. (nglib::Ng_OCC_Load_STEP)

at the end of my function, I am deleting the existing netgen object using 
``` 
nglib::Ng_OCC_DeleteGeometry(ng_geom);
nglib::Ng_DeleteMesh(mesh)

```

I am getting a crash during the following call Ng_DeleteMesh
```
        // Now delete the Mesh class itself
         delete (Mesh*)mesh;
```

error is happening during the delete 

## stacktrace 

![image](https://user-images.githubusercontent.com/1993293/74749459-30e23a00-5238-11ea-958c-5e1b190a2afd.png)

meshclass object is causing a problem during its destruction.  https://github.com/NGSolve/netgen/blob/master/libsrc/meshing/meshclass.cpp#L82

## system 

ubuntu 18.04
clang 6.0
netgen v6.2.1910
oce-dev 0.18.2-2build1 from ubuntu packages

**Comment by ChrLackner** [comment]
Hi, is the mesh class created using a shared_ptr? Then you shouldn't call Ng_DeleteMesh, the mesh will be deleted if all shared_ptr are dead.
Best
Christopher

**Comment by 2564686478** [comment]
hello ，I have also encountered this problem. How did you solve it
