### ISSUE TITLE
Meshing a quad surface failed, What could the problem be?

### ISSUE THREAD

**Issue by XIE-Yao** [NGSolve/netgen#53]
I use nglib to mesh a opencascade TopoDS_Face(generated by BRepFill_Filling from a closed wire), but netgen gives out such a result:

![bad_meshing_result](https://user-images.githubusercontent.com/46967601/75609224-aa83fd00-5b41-11ea-8583-fa15a8c5010d.png)

the four small cube are vertex of the TopoDS_Face, the surface is slightly curved. It seems that netgen cannot find the boundary.

**Comment by ChrLackner** [comment]
Without a reproducible example it is hard to say... I guess the boundaries may not be defined consistently orientated...
