### ISSUE TITLE
Surface meshing for sheets

### ISSUE THREAD

**Issue by nikhilsrajan** [NGSolve/netgen#54]
I want to perform surface meshing on sheets. But in the netgen GUI, when a sheet file is loaded, it doesn't load because in a sheet the boundary triangles have only 2 neighbours. I looked into the C++ API and found the following functions:

- Ng_AddPoint_2D
- Ng_AddBoundarySeg_2D

But they create 2D mesh with only x and y coordinates.

There is Ng_Geometry_2D which is used to expose SplineGeometry2d, but I wasn't sure if this is the data structure for what I wanted to do.

Could you please let me know which data structure and meshing function could be used to perform surface meshing on sheets?

**Comment by ChrLackner** [comment]
It should be possible to use step files of surfaces only and set the final meshing step in the options to optimize surface mesh.
Best
Christopher
