### ISSUE TITLE
Cell count estimation from meshing parameters 

### ISSUE THREAD

**Issue by Vishnu-C** [NGSolve/netgen#57]
There are few meshing parameters to control the mesh generated. Is there any parameter or parameter computation logic to predict/set the number of cells to be generated?
It would be suffice to approximately predict number of cells for given parameters.

Thanks
Vishnu C

**Comment by ChrLackner** [comment]
No there is no such functionality built in and it would be very hard to estimate that for arbitrary geometries a priori. Our meshing parmeters are all locally applied and there is no global information for this.
You can use rules of thumbs like 1./meshsize**n...
