### ISSUE TITLE
Can netgen generate surface mesh  on TopoDS_Face without meshing its boundary wire?

### ISSUE THREAD

**Issue by real-hyperlee** [NGSolve/netgen#59]
Currently if one wants to meshing a opencascade TopoDS_Face, the boudnary wires should be meshed firstly, and passing the mesh nodes into netgen::Mesh object which is what occgenmesh.cpp::OCCFindEdges()  does exactly. 

But I consider the  meshing of boundary wire is not neccessary if the user provides a closed loop of meshed nodes, and then we can project the node on to the TopoDS_Face to form a closed edge loop on UV plane. This offers the same data as OCCFindEdges() do . 

So my question is that will the second way above succeed in netgen?

**Comment by ChrLackner** [comment]
If you mesh the edges yourself, you basically need to reproduce the data structures (segments) that OCCFindEdges does. But then, in principle it should work.
