### ISSUE TITLE
Missing the patch version in NETGEN_VERSION in the NetgenConfig.cmake file

### ISSUE THREAD

**Issue by trelau** [NGSolve/netgen#60]
Should be something like "6.2.2004" instead of just "6.2" or "6.2-dev" in places like this https://github.com/NGSolve/netgen/blob/9ffb22c37fbd13ec6bb499a09a35ff8aa8daa51b/cmake/NetgenConfig.cmake.in#L1

This patch version is used in the [SMESH](https://github.com/LaughlinResearch/SMESH) to define macros that decide which Netgen API to use in the SMESH source based on version number.

**Comment by mhochsteger** [comment]
Fixed with
https://github.com/NGSolve/netgen/commit/267e8b33fb29a590a398ae063abe50331cee0473
https://github.com/NGSolve/netgen/commit/34a6777f496f938e5aa00e856211713f03d32949
