### ISSUE TITLE
valgrind errors

### ISSUE THREAD

**Issue by edward-agapov** [NGSolve/netgen#71]
During porting of NETGEN-plugin of SALOME to NETGEN-6 I faced an error like SIGSEGV. I applied valgrind to my program and it showed me two errors in netgen
1) Invalid read at meshing2.cpp:679
```
      const auto& pout3d = locpoints.Get(pouti);
      locpoints.Append (pout3d);             // <<--- error occures here.
```
`pout3d` is deleted when `locpoints` resizes in `Append()`. To fix, remove & as follows

      auto pout3d = locpoints.Get(pouti);

2) Conditional jump or move depends on uninitialised value at meshing2.cpp:1404
```
     if(maxarea > 0 && meshedarea-meshedarea_before > maxarea)
```
The uninitialised value here is `meshedarea` whose uninitialised value is set at line 361
```     
meshedarea = mesh.SurfaceArea();
```
because `Mesh::CSurfaceArea::area` is not initialized in `CSurfaceArea` constructor

**Comment by ChrLackner** [comment]
Fixed on the current master and in the upcoming release. Thanks for reporting!
