### ISSUE TITLE
Monthly release tags missing

### ISSUE THREAD

**Issue by kkremitzki** [NGSolve/netgen#8]
According to the [Releases](https://ngsolve.org/news/releases) page on the homepage, the monthly releases should be available as tags in the git repo:

> Additionally you can check out the monthly versions on git by checking out the tag of the version (e.g v6.2.1704)

However `git tag -l` only shows `v6.2-dev`, and trying e.g. `git checkout v6.2.1704` doesn't work (as you'd expect based on `git tag -l`.) I am wanting to package netgen for Debian (and ultimately the FreeCAD project which depends on netgen) and it would be helpful if these tags were available.

**Comment by mhochsteger** [comment]
Netgen v6.2.1802 is tagged now and so will be future releases.
