### ISSUE TITLE
SIGSEGV while debug

### ISSUE THREAD

**Issue by edward-agapov** [NGSolve/netgen#80]
Hello

I tried to debug netgen built from v6.2.2101 tag on Debian-10. The program runs OK but debugger catches SIGSEGV at `Mesh` construction, namely when constructing `MemoryTracer` member field. 

    MemoryTracer mem_tracer = {"Mesh",
      points, "points",
      segments, "segments",
      surfelements, "surfelements",
      volelements, "volelements"
    };
valgrind says that `MemoryTracer::id` is used uninitialised. Apparently `MemoryTracer` of either `point` or `segments` or `surfelements` or `volelements` is not yet well constructed by  `mem_tracer` creation, when under debugger.

[valgrind.log](https://github.com/NGSolve/netgen/files/6004308/valgrind.log)

Best regards
Edward

**Comment by aikassir** [comment]
At one stage I was having unexplained SEG faults. Changing the signature of all tracer functions form (string, bool) to (const string&, bool) fixed the issue.

**Comment by ChrLackner** [comment]
Hi, since memory tracing is very much a development feature, we have changed it to only be enabled if TRACE_MEMORY is explicitly set in cmake. Not in debug mode.
