### ISSUE TITLE
Buid netgen failed on docker

### ISSUE THREAD

**Issue by xiaoyaolangzhi** [NGSolve/netgen#82]
I want to compile notgen in Docker, but an error occurs. The content of the Dockerfile is：

FROM ubuntu:16.04
RUN apt-get update && apt-get install -y curl cmake mpich zlib1g-dev libgl1-mesa-dev && \\
    cd /tmp && \\
    curl -O -L https://prdownloads.sourceforge.net/tcl/tcl8.6.11-src.tar.gz && \\
    curl -O -L https://prdownloads.sourceforge.net/tcl/tk8.6.11.1-src.tar.gz && \\
    echo *.tar.gz | xargs -n 1 tar -zxf && rm *.tar.gz && \\
    cd tcl8.6.11/unix && ./configure && make install && \\
    cd ../../tk8.6.11/unix && ./configure && make install && \\
    cd ../../ && rm -rf tcl8.6.11 tk8.6.11 && \\
    curl -O -L http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz && \\
    tar -zxf *.tar.gz && rm *.tar.gz && cd metis-5.1.0 && \\
    sed -i "s/define IDXTYPEWIDTH 32/define IDXTYPEWIDTH 64/g" include/metis.h && \\
    make config prefix=/opt/metis-5.1.0 && make && make install && \\
    cd ../ && rm -rf metis-5.1.0 && \\
    curl -O -L https://github.com/NGSolve/netgen/archive/v6.2.1905.tar.gz && \\
    tar -zxf *.tar.gz && rm *.tar.gz && \\
    cd netgen-6.2.1905 && \\
    cmake -DCMAKE_INSTALL_PREFIX=/opt/netgen-6.2.1905 -DMETIS_DIR=/opt/metis-5.1.0 -DMETIS_LIBRARIES=/opt/metis-5.1.0/lib -DMETIS_INCLUDE_DIRS=/opt/metis-5.1.0/include -DUSE_MPI=OFF -DUSE_GUI=OFF -DUSE_PYTHON=OFF -DUSE_MPI4PY=OFF ./ && \\
    make && make install && \\
    cd ../ && rm -rf netgen-6.2.1905 && \\
    apt-get clean && apt-get -y autoremove && rm -rf /var/lib/apt/lists/*
ENV NETGENDIR=/opt/netgen-6.2.1905/bin

`root@a364cc5f0945:/tmp/netgen-6.2.1905# cmake -DCMAKE_INSTALL_PREFIX=/opt/netgen-6.2.1905 -DMETIS_DIR=/opt/metis-5.1.0 -DMETIS_LIBRARIES=/opt/metis-5.1.0/lib -DMETIS_INCLUDE_DIRS=/opt/metis-5.1.0/include -DUSE_MPI=OFF -DUSE_GUI=OFF -DUSE_PYTHON=OFF -DUSE_MPI4PY=OFF ./`
 for write permissions in install directory...
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Checking for write permissions in install directory...
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/netgen-6.2.1905
`root@a364cc5f0945:/tmp/netgen-6.2.1905# make`
Scanning dependencies of target netgen
[ 10%] Creating directories for 'netgen'
[ 20%] No download step for 'netgen'
[ 30%] No patch step for 'netgen'
[ 40%] No update step for 'netgen'
[ 50%] Performing configure step for 'netgen'
Checking for write permissions in install directory...
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
ubuntu version: xenial

------------------------------------------------------------------------
  Netgen 6.2-21085:  Automatic configuration OK.

  Build type: RelWithDebInfo
  Flags: -O2 -g -DNDEBUG  -march=native

  Enabled functionality:

    OCC: ............... OFF
    JPEGlib: ........... OFF
    FFMPEG: ............ OFF
    GUI: ............... OFF
    MPI: ............... OFF
    PYTHON: ............ OFF

  Building: 

    Type 'make' to compile Netgen.

    Type 'make install' to install Netgen.

  Install directory:

    /opt/netgen-6.2.1905

  Please set the following environment variables:

    NETGENDIR=/opt/netgen-6.2.1905/bin

------------------------------------------------------------------------

-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/netgen-6.2.1905
[ 60%] Performing check_submodules1 step for 'netgen'
[ 70%] Performing check_submodules step for 'netgen'
[ 80%] Performing build step for 'netgen'
make[3]: *** No targets specified and no makefile found.  Stop.
CMakeFiles/netgen.dir/build.make:114: recipe for target 'dependencies/src/netgen-stamp/netgen-build' failed
make[2]: *** [dependencies/src/netgen-stamp/netgen-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/netgen.dir/all' failed
make[1]: *** [CMakeFiles/netgen.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ChrLackner** [comment]
Please try a recent version and not a 2y+ one.
