### ISSUE TITLE
Writable check for CMAKE_INSTALL_DIR is bogus

### ISSUE THREAD

**Issue by StefanBruens** [NGSolve/netgen#83]
For the two typical variants of installing on unix style systems:

1. Using a staging directory, i.e.: `make DESTDIR=/some/staging/dir/ install`
2. Using sudo, i.e.: `sudo make install`

the check for a writable target directory is wrong.

**Comment by mhochsteger** [comment]
Hi,

the writeable check is needed in the superbuild configuration (cmake -DUSE_SUPERBUILD=ON, enabled by default), which automatically installs dependencies of NGSolve (such as Netgen, Mumps, Suitesparse etc.) during the build stage.
For a typical unix-style build configure with -DUSE_SUPERBUILD=OFF and install the dependencies manually (we do this for packaging for instance).

Feel free to reopen if you still experience problems.

**Comment by StefanBruens** [comment]
So this should be guarded by `if (UNIX && USE_SUPERBUILD)`, not only UNIX.

https://github.com/NGSolve/netgen/blob/f5432718c199d75a6d11d66d4b5ecec172c5c635/CMakeLists.txt#L57-L64

**Comment by StefanBruens** [comment]
> Feel free to reopen if you still experience problems.

@mhochsteger - how, if I am not allowed to reopen?

**Comment by mhochsteger** [comment]
> > Feel free to reopen if you still experience problems.
> 
> @mhochsteger - how, if I am not allowed to reopen?

Good point, anyway I got your response.

You are right, I didn't see the check is also done without superbuild. I added your suggestion, thanks for the hint!

Best,
Matthias
