### ISSUE TITLE
Volume mesh optimisation hangs

### ISSUE THREAD

**Issue by massimiliano-leoni** [NGSolve/netgen#88]
Hello!
I experienced that Netgen hangs at the end of the "Optimise volume" meshing step.

To reproduce the issue with the attached mesh
[mesh.vol.gz](https://github.com/NGSolve/netgen/files/6141181/mesh.vol.gz)
:

1. Run Netgen and load the mesh above
2. In Mesh -> Meshing options, set "First Step" to "Optimize Volume" and "Print Messages" to "Most"; Apply changes
3. Click "Generate Mesh"

The mesh optimisation runs, apparently in its entirety, and at some point hangs, in the sense that the progress bar in the lower right corner of the Netgen window does not complete, but CPU usage drops to zero.
Trying to generate another mesh results in an error message saying that a meshing operation is already in progress.
The last bit of output produced reads

```ImproveMesh
 Total badness = 1.75648e+06
 Total badness = 1.75617e+06
 SwapImprove 
 8154 swaps performed
 SwapImprove2 
 0 swaps performed
 ImproveMesh
 Total badness = 1.75102e+06
 Total badness = 1.74554e+06
```

I am using Netgen 6.2-dev, compiled from source.

Thanks for any help!
Massimiliano

**Comment by massimiliano-leoni** [comment]
I attached a much smaller mesh that makes it easier to reproduce the issue.

**Comment by ChrLackner** [comment]
Should be fixed in current master, sorry for the long response time.

**Comment by massimiliano-leoni** [comment]
Thanks! And no worries :)
