### ISSUE TITLE
OpenCascade exception thrown when meshing via nglib

### ISSUE THREAD

**Issue by andrewfu77** [NGSolve/netgen#93]
I'm trying to use nglib to mesh a BRep (or STEP) file from OpenCascade.

I'm building netgen from source, with USE_GUI=OFF, USE_PYTHON=OFF, and USE_OCC=ON, and linking against OpenCascade 7.3.0 (from Open CASCADE Technology).

The following code throws a 'Standard_OutOfRange' exception in the call to Ng_OCC_GenerateSurfaceMesh:

```
#include <cstddef>
namespace nglib {
#include <nglib.h>
}
int main(int, char **) {
    nglib::Ng_Meshing_Parameters params{};
    auto occGeo = nglib::Ng_OCC_Load_BREP("test1.txt");
    auto mesh = nglib::Ng_NewMesh();
    nglib::Ng_OCC_GenerateEdgeMesh(occGeo, mesh, &params);
    nglib::Ng_OCC_GenerateSurfaceMesh(occGeo, mesh, &params);
    nglib::Ng_OCC_DeleteGeometry(occGeo);
    nglib::Ng_DeleteMesh(mesh);
}
```

The exception is thrown from [occgenmesh.cpp:653](https://github.com/NGSolve/netgen/blob/v6.2.2102/libsrc/occ/occgenmesh.cpp#L653), always from the last iteration of the loop. It seems that the number of faces in the mesh doesn't match the number of faces in the geometry (the OCCGeometry::fmap seems to have the correct number of faces, but the Mesh::facedecoding always seems to be one larger). If I comment out this line, [nglib.cpp:105](https://github.com/NGSolve/netgen/blob/v6.2.2102/nglib/nglib.cpp#L105), or create a Ng_Mesh by loading from a dummy file, everything seems to work as expected.

I have attached two example BREPs (the .txt extension is just so that github lets me attach them easily):

[test1.txt](https://github.com/NGSolve/netgen/files/6214305/test1.txt)
[test1_3d.txt](https://github.com/NGSolve/netgen/files/6214307/test1_3d.txt)

**Comment by andrewfu77** [comment]
I see. There always needs to be a call to Ng_OCC_SetLocalMeshSize before generating the mesh.

**Comment by ChrLackner** [comment]
Yes, this creates the meshsize tree.
