### ISSUE TITLE
Can NetGen output grid files in VTK format

### ISSUE THREAD

**Issue by HFH104864** [NGSolve/netgen#95]
Can NetGen output grid files in VTK format

**Comment by mhochsteger** [comment]
No, Netgen cannot output VTK directly, you can either use [meshio](https://github.com/nschloe/meshio) to convert Netgen mesh files or use NGSolve:
https://docu.ngsolve.org/latest/i-tutorials/unit-3.1-parabolic/parabolic.html?highlight=vtk#Supplementary-4:-VTK-Output-(%E2%80%9Cexporting-the-nice-pictures%E2%80%9D)
